### PR TITLE
10 second count down and gmae restet

### PR DESCRIPTION
**Pull request by BUNNshmit**

### CODE REVIEW

**Review by luiskeniosis — COMMENTED** [review]
While this technically resets the plugin, it won't actually reset the world. Meaning any blocks placed/broken will remain.
There are other plugins that can reset the world, so I won't be adding that functionality to this plugin (check out https://www.spigotmc.org/resources/zonerestorer.75630/, or https://www.spigotmc.org/resources/resetworldreboot.81607/).
I do like the idea of being able to reset the plugin without a server restart, I will most likely implement this with a command (/ssrestart) or something similar, rather than having it done automatically.

**Review by luiskeniosis — COMMENTED** [review]
I am currently working on having a config file for the plugin, where the user can set the grace period time, random spread radius, countdown timer etc. Thank you for the suggestion.

**Comment by BUNNshmit** [comment]
i know that it wouldn't reset the world and im ok with that i was wondering if you could still make a version that resets the game though i would really be usefull

**Comment by BUNNshmit** [comment]
please

**Comment by luiskeniosis** [comment]
Hey sorry, i haven't been active. Will make it happen tommorow :)

**Comment by BUNNshmit** [comment]
nice glad to hear it

**Comment by BUNNshmit** [comment]
and thanks for the help!

**Pull request closed without merging**
